package mocks

// Code generated by (wrapping method of mock logger)
import "github.com/goLogOverCoat/pkg/logger/model"

// MockLogger is a wrapper of mock type for the Logger type.
type MockLogger struct {
	Logger
}

// Debug provides a mock function with given fields: msg.
func (_m MockLogger) Debug(msg string) {
	_m.Logger.Debug(msg)
}

// Debugf provides a mock function with given fields: format, args.
func (_m MockLogger) Debugf(format string, args ...interface{}) {
	_m.Logger.Debugf(format, args...)
}

// Error provides a mock function with given fields: msg.
func (_m MockLogger) Error(msg string) {
	_m.Logger.Error(msg)
}

// Errorf provides a mock function with given fields: format, args.
func (_m MockLogger) Errorf(format string, args ...interface{}) {
	_m.Logger.Errorf(format, args...)
}

// Info provides a mock function with given fields: msg.
func (_m MockLogger) Info(msg string) {
	_m.Logger.Info(msg)
}

// Infof provides a mock function with given fields: format, args.
func (_m MockLogger) Infof(format string, args ...interface{}) {
	_m.Logger.Infof(format, args...)
}

// Warn provides a mock function with given fields: msg.
func (_m MockLogger) Warn(msg string) {
	_m.Logger.Warn(msg)
}

// Warnf provides a mock function with given fields: format, args.
func (_m MockLogger) Warnf(format string, args ...interface{}) {
	_m.Logger.Warnf(format, args...)
}

// WithError provides a mock function with given fields: err.
func (_m MockLogger) WithError(err error) model.Logger {
	return _m.Logger.WithError(err)
}

// WithField provides a mock function with given fields: key, value.
func (_m MockLogger) WithField(key string, value interface{}) model.Logger {
	return _m.Logger.WithField(key, value)
}

// WithFields provides a mock function with given fields: fields.
func (_m MockLogger) WithFields(fields model.Fields) model.Logger {
	return _m.Logger.WithFields(fields)
}
